create table if not exists public.logs_acesso (
  id bigint generated by default as identity primary key,
  tipo_usuario text not null
    check (tipo_usuario in ('cliente', 'administrador')),
  identificador text not null,
  proprietario_id bigint
    references public.proprietarios(id) on delete set null,
  veiculo_id bigint
    references public.veiculos(id) on delete set null,
  usuario_concessionaria_id bigint
    references public.usuarios_concessionarias(id) on delete set null,
  concessionaria_id text,
  sucesso boolean not null,
  motivo text,
  criado_em timestamptz not null default now()
);

create index if not exists logs_acesso_tipo_criado_em_idx
  on public.logs_acesso (tipo_usuario, criado_em desc);
create index if not exists logs_acesso_proprietario_id_idx
  on public.logs_acesso (proprietario_id);
create index if not exists logs_acesso_veiculo_id_idx
  on public.logs_acesso (veiculo_id);
create index if not exists logs_acesso_usuario_concessionaria_id_idx
  on public.logs_acesso (usuario_concessionaria_id);
create index if not exists logs_acesso_concessionaria_criado_em_idx
  on public.logs_acesso (concessionaria_id, criado_em desc);

alter table public.logs_acesso enable row level security;

revoke all on table public.logs_acesso from public, anon, authenticated;
revoke all on sequence public.logs_acesso_id_seq from public, anon, authenticated;

grant select, insert on table public.logs_acesso to freeflow_backend;
grant usage, select on sequence public.logs_acesso_id_seq to freeflow_backend;

drop policy if exists freeflow_backend_select on public.logs_acesso;
drop policy if exists freeflow_backend_insert on public.logs_acesso;

create policy freeflow_backend_select on public.logs_acesso
  for select to freeflow_backend using (true);

create policy freeflow_backend_insert on public.logs_acesso
  for insert to freeflow_backend with check (true);
