create table if not exists public.proprietarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text not null unique
);

create table if not exists public.veiculos (
  id bigint generated by default as identity primary key,
  placa text not null unique,
  uid_rfid text unique,
  proprietario_id bigint not null
    references public.proprietarios(id) on delete restrict
);

create table if not exists public.eventos_passagem (
  id bigint generated by default as identity primary key,
  id_veiculo text not null,
  faixa integer not null check (faixa > 0),
  timestamp_evento text not null,
  sensor_id text,
  origem text,
  valor double precision not null default 5.0 check (valor >= 0),
  processado smallint not null default 0 check (processado in (0, 1)),
  anomalia text
);

create table if not exists public.cobrancas (
  id bigint generated by default as identity primary key,
  evento_id bigint not null unique
    references public.eventos_passagem(id) on delete restrict,
  veiculo_id bigint not null
    references public.veiculos(id) on delete restrict,
  valor double precision not null default 5.0 check (valor >= 0),
  status text not null default 'pendente'
    check (status in ('pendente', 'pago')),
  timestamp_criacao text not null
);

create table if not exists public.usuarios_concessionarias (
  id bigint generated by default as identity primary key,
  usuario text not null unique,
  senha_hash text not null,
  concessionaria_id text not null,
  concessionaria_nome text not null,
  faixas_permitidas text not null,
  ativo smallint not null default 1 check (ativo in (0, 1)),
  criado_em text not null
);

create index if not exists veiculos_proprietario_id_idx
  on public.veiculos (proprietario_id);
create index if not exists eventos_passagem_id_veiculo_idx
  on public.eventos_passagem (id_veiculo);
create index if not exists eventos_passagem_faixa_id_idx
  on public.eventos_passagem (faixa, id desc);
create index if not exists eventos_passagem_processado_id_idx
  on public.eventos_passagem (processado, id);
create index if not exists cobrancas_veiculo_id_idx
  on public.cobrancas (veiculo_id);
create index if not exists cobrancas_status_idx
  on public.cobrancas (status);
create index if not exists usuarios_concessionarias_concessionaria_id_idx
  on public.usuarios_concessionarias (concessionaria_id);

alter table public.proprietarios enable row level security;
alter table public.veiculos enable row level security;
alter table public.eventos_passagem enable row level security;
alter table public.cobrancas enable row level security;
alter table public.usuarios_concessionarias enable row level security;

-- A aplicação acessa o Postgres somente pelo backend. Sem políticas, a Data
-- API não disponibiliza registros aos papéis públicos do Supabase.
revoke all on table public.proprietarios from anon, authenticated;
revoke all on table public.veiculos from anon, authenticated;
revoke all on table public.eventos_passagem from anon, authenticated;
revoke all on table public.cobrancas from anon, authenticated;
revoke all on table public.usuarios_concessionarias from anon, authenticated;
